# Generated by Django 4.1.7 on 2023-03-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="view_count",
        ),
        migrations.AddField(
            model_name="room",
            name="is_premium",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
