# Generated by Django 4.1.7 on 2023-04-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_task_description_alter_task_room_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='done',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
