# Generated by Django 4.1.7 on 2023-05-04 13:25

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_task_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='main_picture_path',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.upload_to_room),
        ),
    ]
